server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    username: guest
    password: guest
    url: jdbc:p6spy:mysql://121.199.23.159:3306/houpu_goods
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1 FROM DUAL
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: SpringBootDemoHikariCP
      max-lifetime: 60000
      connection-timeout: 30000
#logging:
#  level:
#    com.houpu.item: debug

mybatis-plus:
  mapper-locations: mappers/*.xml
  type-aliases-package: com.houpu.item.entity
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
    refresh: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true


management:
  # 端点信息接口使用的端口，为了和主系统接口使用的端口进行分离
  server:
    port: 8090
#    servlet:
#      context-path: /sys
  # 端点健康情况，默认值"never"，设置为"always"可以显示硬盘使用情况和线程情况
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  # 设置端点暴露的哪些内容，默认["health","info"]，设置"*"代表暴露所有可访问的端点
  endpoints:
    web:
      exposure:
        include: "*"
